connections:
  mariadb:
    driver: "$jdbc_driver"
    url: "$jdbc_url"
    username: "$jdbc_username"
    password: "$jdbc_password"
    properties:
      # We need to specify the database name already as part of connection, otherwise the login won't work
      databaseName: "$jdbc_db"
