language: java
sudo: false

cache:
  directories:
    - "$HOME/.m2"

services:
  - docker

deploy:
  provider: releases
  file: flowman-dist/target/flowman-dist-*-bin.tar.gz*
  overwrite: true

jobs:
  include:
    - name: Default Build
      jdk: openjdk8
      script: mvn clean install

    - name: Hadoop 2.6 with Spark 2.3
      jdk: openjdk8
      script: mvn clean install -Phadoop-2.6 -Pspark-2.3 -Ddockerfile.skip

    - name: Hadoop 2.7 with Spark 2.3
      jdk: openjdk8
      script: mvn clean install -Phadoop-2.7 -Pspark-2.3 -Ddockerfile.skip

    - name: Hadoop 2.6 with Spark 2.4
      jdk: openjdk8
      script: mvn clean install -Phadoop-2.6 -Pspark-2.4

    - name: Hadoop 2.7 with Spark 2.4
      jdk: openjdk8
      script: mvn clean install -Phadoop-2.7 -Pspark-2.4

    - name: Hadoop 2.7 with Spark 3.0
      jdk: openjdk8
      script: mvn clean install -Phadoop-2.7 -Pspark-3.0

    - name: Hadoop 3.2 with Spark 3.0
      jdk: openjdk8
      script: mvn clean install -Phadoop-3.2 -Pspark-3.0

    - name: Hadoop 2.7 with Spark 3.1
      jdk: openjdk8
      script: mvn clean install -Phadoop-2.7 -Pspark-3.1

    - name: Hadoop 3.2 with Spark 3.1
      jdk: openjdk8
      script: mvn clean install -Phadoop-3.2 -Pspark-3.1

    - name: CDH 5.15
      jdk: openjdk8
      script: mvn clean install -PCDH-5.15 -Ddockerfile.skip

    - name: CDH 6.3
      jdk: openjdk8
      script: mvn clean install -PCDH-6.3 -Ddockerfile.skip
