name: ${plugin.name}
description: ${project.name}
version: ${plugin.version}
isolation: false
jars:
 - hadoop-aws-${hadoop.version}.jar
 - aws-java-sdk-core-${aws.version}.jar
 - aws-java-sdk-kms-${aws.version}.jar
 - aws-java-sdk-s3-${aws.version}.jar
