<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>flowman-common</artifactId>
    <name>Flowman common library</name>
    <description>Flowman common library</description>
    <url>https://flowman.io</url>

    <parent>
	    <groupId>com.dimajix.flowman</groupId>
	    <artifactId>flowman-root</artifactId>
        <version>1.4.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <build>
        <plugins>
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.scalatest</groupId>
                <artifactId>scalatest-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.basedir}/src/main/scala-${scala.api_version}</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>add-site-source</id>
                        <phase>pre-site</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.basedir}/src/main/scala-${scala.api_version}</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>default-scala-2.13</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <dependencies>
                <!--
                    We can only include scala-parallel-collections for scala 2.13 other
                    Otherwise it will break the build for scala 2.12
                -->
                <dependency>
                    <groupId>org.scala-lang.modules</groupId>
                    <artifactId>scala-parallel-collections_2.13</artifactId>
                    <version>1.2.0</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>spark-3.0</id>
        </profile>
        <profile>
            <id>spark-3.1</id>
        </profile>
        <profile>
            <id>spark-3.2</id>
        </profile>
        <profile>
            <id>spark-3.3</id>
        </profile>
        <profile>
            <id>spark-3.4</id>
        </profile>
        <profile>
            <id>spark-3.5</id>
        </profile>
        <profile>
            <id>spark-4.0</id>
            <dependencies>
                <dependency>
                    <groupId>org.scala-lang.modules</groupId>
                    <artifactId>scala-parallel-collections_2.13</artifactId>
                    <version>1.2.0</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>spark-4.1</id>
            <dependencies>
                <dependency>
                    <groupId>org.scala-lang.modules</groupId>
                    <artifactId>scala-parallel-collections_2.13</artifactId>
                    <version>1.2.0</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>scala-2.13</id>
            <activation>
                <property>
                    <name>scala.api_version</name>
                    <value>2.13</value>
                </property>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>org.scala-lang.modules</groupId>
                    <artifactId>scala-parallel-collections_2.13</artifactId>
                    <version>1.2.0</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>scala-2.12</id>
            <activation>
                <property>
                    <name>scala.api_version</name>
                    <value>2.12</value>
                </property>
            </activation>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>com.dimajix.flowman</groupId>
            <artifactId>flowman-scalatest-compat</artifactId>
        </dependency>
        <dependency>
            <groupId>com.dimajix.flowman</groupId>
            <artifactId>flowman-common-java</artifactId>
        </dependency>

        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-reflect</artifactId>
        </dependency>

        <dependency>
            <groupId>org.scala-lang.modules</groupId>
            <artifactId>scala-collection-compat_${scala.api_version}</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>${log4j.slf4j-impl}</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-scala_${scala.api_version}</artifactId>
        </dependency>

        <dependency>
            <groupId>org.scalatest</groupId>
            <artifactId>scalatest_${scala.api_version}</artifactId>
        </dependency>
        <dependency>
            <groupId>org.scalamock</groupId>
            <artifactId>scalamock_${scala.api_version}</artifactId>
        </dependency>
    </dependencies>
</project>
